In [1]:
import numpy as np 

In [2]:
def convert_csv_np(file_path):
    return np.genfromtxt(file_path, delimiter=',')
def files_in_dir(folder):
    ordered_list = []
    file_list = os.listdir(folder)
    for i in range(len(file_list)):
        ordered_list.append(folder +str(i)+".csv")
    return ordered_list
def get_all_data(folder):
    file_list = files_in_dir(folder)
    x,y = [],[]
    for i in file_list:
        data = convert_csv_np(i)
        temp_x,temp_y = get_data_label(data)
#         print(temp_x.shape)
#         print(temp_y.shape)
#         break
        x.append(temp_x)
        y.append(temp_y)
#     print(len(x))
    return np.asarray(x),np.asarray(y)
def get_data_label(data):
    label = data[:,1024]
    data = np.delete(data,1024,axis=1)
    return data, label

In [3]:
import os 
folder = '../data/neg_vs_net/male_0/'
fx,fy = get_all_data(folder)

In [4]:
raw_x,raw_y = fx[0],fy[0]


In [5]:
raw_x.shape

(192, 1024)

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
parameters = {'max_depth': [2, 5, 10,None],
                   'n_estimators': [100, 256, 512],
                   'bootstrap': [True, False],
                    'min_impurity_decrease':[0.025,0.0]}
boost_parameters = {'max_depth': [3, 5, 7],
                   'n_estimators': [100, 256],
                    "learning_rate":[0.1,0.05],
                    "gamma":[0,0.0001,0.01]}
rf_model = RandomForestClassifier(criterion='entropy', # How to train the trees. Also supports entropy.           
                                   min_samples_split=2, # Minimum samples to create a split.
                                   min_samples_leaf=0.001, # Minimum samples in a leaf. Accepts fractions for %. This is 0.1% of sample.
                                   min_weight_fraction_leaf=0.0, # Same as above, but uses the class weights.
                                   max_features='auto', # Maximum number of features per split (not tree!) by default is sqrt(vars)
                                   max_leaf_nodes=None, # Maximum number of nodes.
                                   oob_score=True,  # If report accuracy with non-selected cases.
                                   n_jobs=-1, # Parallel processing. Set to -1 for all cores. Watch your RAM!!
                                   verbose=1, # If to give info during training. Set to 0 for silent training.
                                   warm_start=False, # If train over previously trained tree.
                                   class_weight='balanced',
                                    )
boosting = XGBClassifier(verbosity=1,                  # If to show more errors or not.
                            objective='binary:logistic',  # Type of target variable.
                            booster='gbtree',             # What to boost. Trees in this case.
                            n_jobs=2,                     # Parallel jobs to run. Set your processor number.
                            subsample=0.5,                  # Subsample ratio. Can set lower
                            colsample_bytree=1,           # Subsample ratio of columns when constructing each tree.
                            colsample_bylevel=1,          # Subsample ratio of columns when constructing each level. 0.33 is similar to random forest.
                            colsample_bynode=1,           # Subsample ratio of columns when constructing each split.
                            reg_alpha=1,                  # Regularizer for first fit. alpha = 1, lambda = 0 is LASSO.
                            reg_lambda=0,                 # Regularizer for first fit.
                            scale_pos_weight=1,           # Balancing of positive and negative weights.
                            base_score=0.5,               # Global bias. Set to average of the target rate.
                            missing=None                  # How are nulls encoded?
                            )
def perform_grid_search(x,y,type):
    if type=="rf":
        model = GridSearchCV(rf_model, parameters, scoring='roc_auc', n_jobs=-1)
    else:
        model = GridSearchCV(boosting, boost_parameters, scoring='roc_auc', n_jobs=-1)
    model.fit(x,y)
    # clf.cv_results_['mean_test_score'],
    return model.best_params_

In [13]:
params = perform_grid_search(raw_x,raw_y,"rf")

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.2s finished


In [14]:
params

{'bootstrap': True,
 'max_depth': 5,
 'min_impurity_decrease': 0.025,
 'n_estimators': 100}

In [15]:
params1 = perform_grid_search(raw_x,raw_y,"")

TypeError: perform_grid_search() missing 1 required positional argument: 'type'

In [ ]:
params1

In [16]:
param2 = perform_grid_search(raw_x,raw_y,"boosting")

In [17]:
param2

{'gamma': 0.01, 'learning_rate': 0.05, 'max_depth': 5, 'n_estimators': 256}

In [18]:
def model_training(params,type,x,y):
    if type=="rf":
        model = RandomForestClassifier(max_depth=params['max_depth'],
                                        n_estimators=params['n_estimators'],
                                        min_impurity_decrease=params['min_impurity_decrease'],
                                        bootstrap=params['bootstrap'],
                                        criterion='entropy', # How to train the trees. Also supports entropy.           
                                        min_samples_split=2, # Minimum samples to create a split.
                                        min_samples_leaf=0.001, # Minimum samples in a leaf. Accepts fractions for %. This is 0.1% of sample.
                                        min_weight_fraction_leaf=0.0, # Same as above, but uses the class weights.
                                        max_features='auto', # Maximum number of features per split (not tree!) by default is sqrt(vars)
                                        max_leaf_nodes=None, # Maximum number of nodes.
                                        oob_score=True,  # If report accuracy with non-selected cases.
                                        n_jobs=-1, # Parallel processing. Set to -1 for all cores. Watch your RAM!!
                                        verbose=1, # If to give info during training. Set to 0 for silent training.
                                        warm_start=False, # If train over previously trained tree.
                                        class_weight='balanced',
                                        )
    else:
        model= XGBClassifier(max_depth=params['max_depth'],
                        n_estimators=params['n_estimators'],
                        learning_rate=params['learning_rate'],
                        gamma=params['gamma'],
                        verbosity=1,                  # If to show more errors or not.
                        objective='binary:logistic',  # Type of target variable.
                        booster='gbtree',             # What to boost. Trees in this case.
                        n_jobs=2,                     # Parallel jobs to run. Set your processor number.
                        subsample=0.5,                  # Subsample ratio. Can set lower
                        colsample_bytree=1,           # Subsample ratio of columns when constructing each tree.
                        colsample_bylevel=1,          # Subsample ratio of columns when constructing each level. 0.33 is similar to random forest.
                        colsample_bynode=1,           # Subsample ratio of columns when constructing each split.
                        reg_alpha=1,                  # Regularizer for first fit. alpha = 1, lambda = 0 is LASSO.
                        reg_lambda=0,                 # Regularizer for first fit.
                        scale_pos_weight=1,           # Balancing of positive and negative weights.
                        base_score=0.5,               # Global bias. Set to average of the target rate.
                        missing=None                  # How are nulls encoded?
                        )
    model.fit(x,y)
    return model
        

In [21]:
m = model_training(params,'rf',raw_x,raw_y)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.1s finished


In [27]:
m1 = model_training(param2,'boosting',raw_x,raw_y)

In [23]:
m.predict(raw_x)

[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 100 out of 100 | elapsed:    0.0s finished


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [31]:
m.predict(raw_x)

[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 100 out of 100 | elapsed:    0.0s finished


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [32]:
m.feature_importances_

array([0.00183879, 0.00033148, 0.        , ..., 0.00020538, 0.00170342,
       0.00021831])

In [24]:
m.feature_importances_

array([0.00112607, 0.00101051, 0.        , ..., 0.00244139, 0.00207762,
       0.00269315])

In [26]:
def get_coefs(model):
    return model.feature_importances_
get_coefs(m)

array([0.00112607, 0.00101051, 0.        , ..., 0.00244139, 0.00207762,
       0.00269315])

In [89]:
def get_predicts(x_train,x_test,model):
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)
    return y_train_pred,y_test_pred

In [28]:
t = get_predicts(raw_x,raw_x,raw_y,raw_y,m)


[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 100 out of 100 | elapsed:    0.0s finished


tuple

In [41]:
import pymongo

ModuleNotFoundError: No module named 'pymongo'

In [35]:
import pymongo

client = pymongo.MongoClient(
    "mongodb+srv://capitalallen:allen123@cluster0.bc8gt.mongodb.net/<dbname>?retryWrites=true&w=majority")
db = client.get_database('eeg')
records = db.results
name = '../data/neg_vs_net/male_0/'
cv = "1"
data = {}
data['name'] = '../data/neg_vs_net/male_0/'
data[cv] = {}
data[cv]['raw_data'] = {}
data[cv]['coefs'] = (m.feature_importances_.tolist())
data[cv]['y_train'] = raw_y.tolist()
data[cv]['y_train_pred'] = raw_y.tolist()
data[cv]['y_test'] = raw_y.tolist()
data[cv]['y_test_pred'] = raw_y.tolist()
data[cv]['metrics'] = {}
records.insert_one(data)

In [39]:
import Load_csv_data as lcd 
import train 

def test():
    # load data 
    folder = '../data/neg_vs_net/male_0/'
    get_data = lcd.Load_data() 
    x,y = get_data.get_all_data(folder)
    return x,y
x,y = test()

In [40]:
x.shape

(19,)

In [79]:
cv = x.size
def get_x_train_test(index,data):
    train,test = None,None
    train = data[0] if index !=0 else data[1]
    for i in range(data.size):
        if i == index:
            test = data[i]
        else:
            train = np.concatenate((train,data[i]),axis=0)
    return train,test
def get_y_train_test(index,data):
    train,test = None,None
    train = data[0] if index !=0 else data[1]
    for i in range(data.size):
        if i == index:
            test = data[i]
        else:
            train = np.concatenate((train,data[i]),axis=0)
    return train,test
# for i in range(cv):
#     shape = x[i].shape
#     print(shape)
#     temp = np.concatenate((x[:i],x[i+1:]))
#     print(temp.shape)
#     xtrain,xtest = np.concatenate((x[:i],x[i+1:])).reshape((cv-1)*shape[0],shape[1]),x[i].reshape(shape[0],shape[1])
#     ytrain,ytest = np.concatenate((y[:i],y[i+1:])).reshape((cv-1)*shape[0]),y[i].reshape(shape[0]) 
#     print(x_train.shape)
#     print(xtest.shape)
#     print(ytrain.shape)
#     print(ytest.shape)
#     break
               

In [80]:
x_train,x_test = get_x_train_test(0,x)
y_train,y_test = get_y_train_test(0,y)
# temp = np.concatenate((x[:0],x[0+1:])).reshape((cv-1,1))


In [82]:
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(3540, 1024) (192, 1024)
(3540,) (192,)


In [53]:
t = temp[:][:]

In [54]:
t.shape

(18, 1)

In [85]:
import Load_csv_data as lcd 
import train 
def get_x_all(data):
    x = data[0]
    for i in range(1,data.size):
        x = np.concatenate((x,data[i]),axis=0)
    return x

def get_y_all(data):
    y = data[0]
    for i in range(1,data.size):
        y = np.concatenate((y,data[i]),axis=0)
    return y  

def get_x_train_test(index,data):
    train,test = None,None
    train = data[0] if index !=0 else data[1]
    for i in range(data.size):
        if i == index:
            test = data[i]
        else:
            train = np.concatenate((train,data[i]),axis=0)
    return train,test

def get_y_train_test(index,data):
    train,test = None,None
    train = data[0] if index !=0 else data[1]
    for i in range(data.size):
        if i == index:
            test = data[i]
        else:
            train = np.concatenate((train,data[i]),axis=0)
    return train,test

def run_train():
    # load data 
    folder = '../data/neg_vs_net/male_0/'
    type = 'rf'
    get_data = lcd.Load_data() 
    x,y = get_data.get_all_data(folder)
    x = x[:2]
    y = y[:2]
    cv = x.size
    # init class
    train_model = train.Train(folder)
    
    # perform grid search
    
    train_model.perform_grid_search(get_x_all(x),get_y_all(y),type)
    for i in range(cv):
        # type,cv_num,x_train,y_train,x_test,y_test
        x_train,x_test = get_x_train_test(i,x)
        y_train,y_test = get_y_train_test(i,y)
        # type,cv_num,x_train,y_train,x_test,y_test
        train_model.ex_train(type,str(i),x_train,y_train,x_test,y_test)

In [91]:

name, cv, coefs, y_trian,y_train_pred,y_test,y_test_pred = run_train()

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done 256 out of 256 | elapsed:    0.3s finished
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done 256 out of 256 | elapsed:    0.3s finished


TypeError: get_predicts() takes 4 positional arguments but 5 were given